select [Percent],Period, * from Categories

select * from Locations
select * from Rooms
select * from Items

IF NOT EXISTS (SELECT * FROM GENMASTER where GENFLAG = 1)
BEGIN
PRINT 'INSERT GENMASTER 1'
	Insert Into GENMASTER VALUES (0,'Baik',0,1,'SYSTEM',GETDATE())
	Insert Into GENMASTER VALUES (1,'Rusak Dapat Diperbaiki',1,1,'SYSTEM',GETDATE())
	Insert Into GENMASTER VALUES (2,'Rusak Berat',2,1,'SYSTEM',GETDATE())
END

IF NOT EXISTS (SELECT * FROM GENMASTER where GENFLAG = 2)
BEGIN
PRINT 'INSERT GENMASTER 2'
	Insert Into GENMASTER VALUES (0,'Aktif',0,2,'SYSTEM',GETDATE())
	Insert Into GENMASTER VALUES (1,'Dimusnahkan',1,2,'SYSTEM',GETDATE())
	Insert Into GENMASTER VALUES (2,'Hilang',2,2,'SYSTEM',GETDATE())
END

IF NOT EXISTS (SELECT * FROM GENMASTER where GENFLAG = 3)
BEGIN
PRINT 'INSERT GENMASTER 3'
	Insert Into GENMASTER VALUES (0,'Pemerintah',0,3,'SYSTEM',GETDATE())
	Insert Into GENMASTER VALUES (1,'Yayasan',1,3,'SYSTEM',GETDATE())
	Insert Into GENMASTER VALUES (2,'Hibah Alumni',2,3,'SYSTEM',GETDATE())
END

IF NOT EXISTS (SELECT * FROM GENMASTER where GENFLAG = 4)
BEGIN
PRINT 'INSERT GENMASTER 4'
	Insert Into GENMASTER VALUES (0,'Room Available',0,4,'SYSTEM',GETDATE())
	Insert Into GENMASTER VALUES (1,'Waiting Approval',1,4,'SYSTEM',GETDATE())
	Insert Into GENMASTER VALUES (2,'Approved',2,4,'SYSTEM',GETDATE())
	Insert Into GENMASTER VALUES (3,'Rejected',3,4,'SYSTEM',GETDATE())
END

IF NOT EXISTS (SELECT * FROM GENMASTER where GENFLAG = 5)
BEGIN
PRINT 'INSERT GENMASTER 5'
	Insert Into GENMASTER VALUES (0,'Tersedia',0,5,'SYSTEM',GETDATE())
	Insert Into GENMASTER VALUES (1,'Menunggu Persetujuan',1,5,'SYSTEM',GETDATE())
	Insert Into GENMASTER VALUES (2,'Siap Digunakan',2,5,'SYSTEM',GETDATE())
END

IF NOT EXISTS (SELECT * FROM GENMASTER where GENFLAG = 6)
BEGIN
PRINT 'INSERT GENMASTER 6'
	Insert Into GENMASTER VALUES (0,'Waiting approved',0,6,'SYSTEM',GETDATE())
	Insert Into GENMASTER VALUES (1,'Approved',1,6,'SYSTEM',GETDATE())
	Insert Into GENMASTER VALUES (2,'Rejected',2,6,'SYSTEM',GETDATE())
END

--create user [IIS APPPOOL\SarPrasApp] for login [IIS APPPOOL\SarPrasApp]
--go
--execute sp_addrolemember N'db_owner', N'IIS APPPOOL\SarPrasApp'
--go
